services:
  web:
    build:
      context: .
    depends_on:
      - db
    working_dir: /workspace
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - .:/workspace
      - ./addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    command:
      - --config=/etc/odoo/odoo.conf
  db:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
  pgadmin-data:
